Update OCV-PR-Windows.yaml

diff --git a/.github/workflows/OCV-PR-Windows.yaml b/.github/workflows/OCV-PR-Windows.yaml
--- a/.github/workflows/OCV-PR-Windows.yaml
+++ b/.github/workflows/OCV-PR-Windows.yaml
@@ -1,161 +1,271 @@
-name: OCV PR Windows
+# name: OCV PR Windows
+
+# on:
+#   pull_request:
+#     branches:
+#       - main
+#     paths:
+#       - '.github/workflows/OCV-PR-Windows.yaml'
+#       - 'checkout-and-merge/*'
+#       - 'configure-and-build/*'
+#       - 'run-tests/*'
+#       - 'scripts/runner.py'
+#       - 'scripts/test-plan.json'
+#   workflow_call:
+#     inputs:
+#       workflow_branch:
+#         description: "Branch for ci-gha-workflow repository"
+#         default: "main"
+#         required: false
+#         type: string
+
+# concurrency:
+#   group: OCV-PR-Windows-${{ github.ref }}
+#   cancel-in-progress: true
+
+# jobs:
+
+#   branch_eval:
+#     runs-on: ubuntu-24.04
+#     outputs:
+#       branches: ${{ steps.determine-branches.outputs.branches }}
+#     steps:
+#       - id: determine-branches
+#         shell: bash
+#         run: |
+#           if [ "${{ github.event.repository.name == 'ci-gha-workflow' }}" = "true" ] ; then
+#             echo "branches=[ '4.x', '5.x' ]" >> "$GITHUB_OUTPUT"
+#           else
+#             echo "branches=[ '' ]" >> "$GITHUB_OUTPUT"
+#           fi
+
+#   Windows:
+#     runs-on: ${{ matrix.runner }}
+#     needs: branch_eval
+
+#     strategy:
+#       fail-fast: false
+#       max-parallel: 2
+#       matrix:
+#         arch: [ arm64 ]
+#         config: [ base ]
+#         include:
+#           - arch: arm64
+#             config: base
+#             runner: windows-11-arm
+#             vs: 'Visual Studio 17 2022'
+#             cmake_arch: ARM64
+#             no_opencl: true
+#         branch: ${{ fromJSON(needs.branch_eval.outputs.branches )}}
+
+#     defaults:
+#       run:
+#         shell: bash
+
+#     env:
+#       CMAKE_OPT: >-
+#         -DCL_Z_OPTION=/Z7
+#         -DBUILD_EXAMPLES=ON
+#         -DOPENCV_ENABLE_NONFREE=ON
+#         ${{ matrix.no_opencl && '-DWITH_OPENCL=OFF' || '' }}
+#         ${{ matrix.arch == 'arm64' && '-DWITH_VULKAN=OFF -DBUILD_opencv_vulkan=OFF -DOPENCV_DNN_VULKAN=OFF -DBUILD_opencv_world=ON -DWITH_ITT=OFF -DWITH_OPENCL=OFF -DWITH_OPENCLAMDBLAS=OFF -DWITH_OPENCLAMDFFT=OFF -DWITH_OPENCL_D3D11_NV=OFF -DWITH_DIRECTML=OFF -DWITH_DIRECTX=OFF -DWITH_ADE=OFF -DCMAKE_DISABLE_FIND_PACKAGE_Vulkan=ON' || '' }}
+
+#       MAIN_BUILD_DIR: build
+#       OPENCV_FOR_THREADS_NUM: 8
+#       CMAKE_BUILD_PARALLEL_LEVEL: 8
+
+#     steps:
+
+#     - name: Propagate environment
+#       run: |
+#         echo "GIT_CACHE=$(cygpath -u "$GIT_CACHE")" >> "$GITHUB_ENV"
+#         echo "DNN_MODELS=$(cygpath -u "$DNN_MODELS")" >> "$GITHUB_ENV"
+#         echo "BINARIES_CACHE=$(cygpath -u "$BINARIES_CACHE")" >> "$GITHUB_ENV"
+#         echo "OPENCV_DOWNLOAD_PATH=$(cygpath -u "$BINARIES_CACHE")" >> "$GITHUB_ENV"
+
+#     - name: Checkout workflow repository
+#       uses: actions/checkout@v4
+#       with:
+#         repository: pratham-mcw/ci-gha-workflow_dummy
+#         ref: "${{ github.repository == 'pratham-mcw/ci-gha-workflow_dummy' && github.ref || inputs.workflow_branch }}"
+
+#     - name: Checkout and merge OpenCV
+#       uses: ./checkout-and-merge
+#       with:
+#         target_branch: '4.x'
+#         author: pratham-mcw
+#         source_branch: ${{ github.head_ref }}
+#         gitcache: '${{ env.GIT_CACHE }}'
+#         workdir: '${{ github.workspace }}'
+
+#     - name: Clone opencv_extra
+#       run: |
+#         rm -rf opencv_extra
+#         git clone --single-branch --branch 4.x https://github.com/pratham-mcw/opencv_extra.git
+#         cd opencv_extra
+#         git config user.email "opencv.ci"
+#         git config user.name "opencv.ci"
+
+#     - name: Install Python dependencies
+#       run: |
+#         python -m pip install --upgrade pip
+#         python -m pip install requests
+
+#     - name: Update extra dnn models
+#       timeout-minutes: 60
+#       run: |
+#         python opencv_extra/testdata/dnn/download_models.py \
+#           --cleanup \
+#           --dst '${{ env.DNN_MODELS }}/dnn'
+#         echo "OPENCV_DNN_TEST_DATA_PATH=${{ env.DNN_MODELS }}" >> $GITHUB_ENV
+
+#     - name: Configure and build OpenCV
+#       uses: ./configure-and-build
+#       with:
+#         workdir: '${{ github.workspace }}'
+#         builddir: 'build'
+#         generator: '${{ matrix.vs }}'
+#         options: '-A ${{ matrix.cmake_arch }} ${{ env.CMAKE_OPT }}'
+
+#     - name: Configure and build OpenCV with contrib
+#       uses: ./configure-and-build
+#       with:
+#         workdir: '${{ github.workspace }}'
+#         builddir: 'build-contrib'
+#         generator: '${{ matrix.vs }}'
+#         options: '-A ${{ matrix.cmake_arch }} -DCMAKE_BUILD_TYPE=Release -DOPENCV_EXTRA_MODULES_PATH=opencv_contrib/modules ${{ env.CMAKE_OPT }}'
+
+#     - name: Run OpenCV tests
+#       uses: ./run-tests
+#       env:
+#         OPENCV_TEST_DATA_PATH: '${{ github.workspace }}/opencv_extra/testdata'
+#         OPENCV_TEST_REQUIRE_DATA: 1
+#         OPENCV_TEST_CHECK_OPTIONAL_DATA: 1
+#         PYTHONPATH: '${{ github.workspace }}/${{ env.MAIN_BUILD_DIR }}/python_loader:$PYTHONPATH'
+#       with:
+#         workdir: '${{ github.workspace }}'
+#         builddir: '${{ env.MAIN_BUILD_DIR }}'
+#         logdir: '${{ github.workspace }}'
+#         plan: "test-plan-win-4.x.json"
+#         suite: "[ ${{ (github.event.repository.name == 'opencv_contrib') && '''contrib''' || '''main''' }} ]"
+#         enable_python: "false"
+#         enable_java: "false"
+#         filter: "[ 'windows-common' ]"
+#         suffix: "${{ matrix.arch }}_4.x"
+#         timeout: 15
+
+#     - if: ${{ always() && env.WARNINGS == '1' }}
+#       name: Warnings check
+#       run: |
+#         echo "::error Warnings have been found!"
+#         exit 1
+name: OpenCV Local Exact Steps (Windows ARM64)
 
 on:
   pull_request:
-    branches:
-      - main
-    paths:
-      - '.github/workflows/OCV-PR-Windows.yaml'
-      - 'checkout-and-merge/*'
-      - 'configure-and-build/*'
-      - 'run-tests/*'
-      - 'scripts/runner.py'
-      - 'scripts/test-plan.json'
-  workflow_call:
-    inputs:
-      workflow_branch:
-        description: "Branch for ci-gha-workflow repository"
-        default: "main"
-        required: false
-        type: string
-
-concurrency:
-  group: OCV-PR-Windows-${{ github.ref }}
-  cancel-in-progress: true
+  push:
+    branches: [ main ]
 
 jobs:
+  windows:
+    runs-on: windows-11-arm
 
-  branch_eval:
-    runs-on: ubuntu-24.04
-    outputs:
-      branches: ${{ steps.determine-branches.outputs.branches }}
-    steps:
-      - id: determine-branches
-        shell: bash
-        run: |
-          if [ "${{ github.event.repository.name == 'ci-gha-workflow' }}" = "true" ] ; then
-            echo "branches=[ '4.x', '5.x' ]" >> "$GITHUB_OUTPUT"
-          else
-            echo "branches=[ '' ]" >> "$GITHUB_OUTPUT"
-          fi
+env:
+  OPENCV_ROOT: ${{ github.workspace }}\OPENCV
 
-  Windows:
-    runs-on: ${{ matrix.runner }}
-    needs: branch_eval
+steps:
+  - name: Create OPENCV folder
+    shell: cmd
+    run: mkdir OPENCV
 
-    strategy:
-      fail-fast: false
-      max-parallel: 2
-      matrix:
-        arch: [ arm64 ]
-        config: [ base ]
-        include:
-          - arch: arm64
-            config: base
-            runner: windows-11-arm
-            vs: 'Visual Studio 17 2022'
-            cmake_arch: ARM64
-            no_opencl: true
-        branch: ${{ fromJSON(needs.branch_eval.outputs.branches )}}
+  - name: Clone OpenCV
+    shell: cmd
+    working-directory: OPENCV
+    run: |
+      git clone https://github.com/opencv/opencv.git
+      cd opencv
+      git checkout 4.x
 
-    defaults:
-      run:
-        shell: bash
+  - name: Clone OpenCV Contrib
+    shell: cmd
+    working-directory: OPENCV
+    run: |
+      git clone https://github.com/opencv/opencv_contrib.git
+      cd opencv_contrib
+      git checkout 4.x
 
-    env:
-      CMAKE_OPT: >-
-        -DCL_Z_OPTION=/Z7
-        -DBUILD_EXAMPLES=ON
-        -DOPENCV_ENABLE_NONFREE=ON
-        ${{ matrix.no_opencl && '-DWITH_OPENCL=OFF' || '' }}
-        ${{ matrix.arch == 'arm64' && '-DWITH_VULKAN=OFF -DBUILD_opencv_vulkan=OFF -DOPENCV_DNN_VULKAN=OFF -DBUILD_opencv_world=ON -DWITH_ITT=OFF -DWITH_OPENCL=OFF -DWITH_OPENCLAMDBLAS=OFF -DWITH_OPENCLAMDFFT=OFF -DWITH_OPENCL_D3D11_NV=OFF -DWITH_DIRECTML=OFF -DWITH_DIRECTX=OFF -DWITH_ADE=OFF -DCMAKE_DISABLE_FIND_PACKAGE_Vulkan=ON' || '' }}
+  - name: Clone OpenCV Extra
+    shell: cmd
+    working-directory: OPENCV
+    run: |
+      git clone https://github.com/opencv/opencv_extra.git
+      cd opencv_extra
+      git checkout 4.x
 
-      MAIN_BUILD_DIR: build
-      OPENCV_FOR_THREADS_NUM: 8
-      CMAKE_BUILD_PARALLEL_LEVEL: 8
+  - name: Setup DNN test data
+    shell: cmd
+    run: |
+      mkdir dnn
+      cd dnn
+      pip install requests
+      python %OPENCV_ROOT%\opencv_extra\testdata\dnn\download_models.py
 
-    steps:
+  - name: Configure environment variables
+    shell: cmd
+    run: |
+      echo OPENCV_DNN_TEST_DATA_PATH=%cd%>> %GITHUB_ENV%
+      echo OPENCV_TEST_DATA_PATH=%OPENCV_ROOT%\opencv_extra\testdata>> %GITHUB_ENV%
 
-    - name: Propagate environment
-      run: |
-        echo "GIT_CACHE=$(cygpath -u "$GIT_CACHE")" >> "$GITHUB_ENV"
-        echo "DNN_MODELS=$(cygpath -u "$DNN_MODELS")" >> "$GITHUB_ENV"
-        echo "BINARIES_CACHE=$(cygpath -u "$BINARIES_CACHE")" >> "$GITHUB_ENV"
-        echo "OPENCV_DOWNLOAD_PATH=$(cygpath -u "$BINARIES_CACHE")" >> "$GITHUB_ENV"
+  - name: Configure OpenCV
+    shell: cmd
+    working-directory: OPENCV\opencv
+    run: >
+      cmake -S . -B build -G "Visual Studio 17 2022"
+      -DCMAKE_BUILD_TYPE=Release
+      -DBUILD_opencv_world=ON
+      -DWITH_ITT=OFF
+      -DWITH_OPENCL=OFF
+      -DWITH_OPENCLAMDBLAS=OFF
+      -DWITH_OPENCLAMDFFT=OFF
+      -DWITH_OPENCL_D3D11_NV=OFF
+      -DWITH_DIRECTML=OFF
+      -DWITH_DIRECTX=OFF
+      -DWITH_ADE=OFF
+      -DCPU_BASELINE="NEON"
+      -DBUILD_opencv_python3=ON
+      -DOPENCV_EXTRA_MODULES_PATH="%OPENCV_ROOT%\opencv_contrib\modules"
 
-    - name: Checkout workflow repository
-      uses: actions/checkout@v4
-      with:
-        repository: pratham-mcw/ci-gha-workflow_dummy
-        ref: "${{ github.repository == 'pratham-mcw/ci-gha-workflow_dummy' && github.ref || inputs.workflow_branch }}"
+  - name: Build OpenCV
+    shell: cmd
+    working-directory: OPENCV\opencv\build
+    run: cmake --build . --config Release --parallel
 
-    - name: Checkout and merge OpenCV
-      uses: ./checkout-and-merge
-      with:
-        target_branch: '4.x'
-        author: pratham-mcw
-        source_branch: ${{ github.head_ref }}
-        gitcache: '${{ env.GIT_CACHE }}'
-        workdir: '${{ github.workspace }}'
+  - name: Install OpenCV
+    shell: cmd
+    working-directory: OPENCV\opencv\build
+    run: cmake --build . --target INSTALL --config Release
 
-    - name: Clone opencv_extra
-      run: |
-        rm -rf opencv_extra
-        git clone --single-branch --branch 4.x https://github.com/pratham-mcw/opencv_extra.git
-        cd opencv_extra
-        git config user.email "opencv.ci"
-        git config user.name "opencv.ci"
+  # ===========================
+  # Run OpenCV functionality tests
+  # ===========================
+  - name: Run opencv_test binaries
+    shell: cmd
+    working-directory: OPENCV\opencv\build\bin\Release
+    run: |
+      for %f in (opencv_test_*.exe) do (
+        echo Running %f
+        "%f"
+      )
 
-    - name: Install Python dependencies
-      run: |
-        python -m pip install --upgrade pip
-        python -m pip install requests
+  # ===========================
+  # Run OpenCV performance tests
+  # ===========================
+  - name: Run opencv_perf binaries
+    shell: cmd
+    working-directory: OPENCV\opencv\build\bin\Release
+    run: |
+      for %f in (opencv_perf_*.exe) do (
+        echo Running %f
+        "%f"
+      )
 
-    - name: Update extra dnn models
-      timeout-minutes: 60
-      run: |
-        python opencv_extra/testdata/dnn/download_models.py \
-          --cleanup \
-          --dst '${{ env.DNN_MODELS }}/dnn'
-        echo "OPENCV_DNN_TEST_DATA_PATH=${{ env.DNN_MODELS }}" >> $GITHUB_ENV
-
-    - name: Configure and build OpenCV
-      uses: ./configure-and-build
-      with:
-        workdir: '${{ github.workspace }}'
-        builddir: 'build'
-        generator: '${{ matrix.vs }}'
-        options: '-A ${{ matrix.cmake_arch }} ${{ env.CMAKE_OPT }}'
-
-    - name: Configure and build OpenCV with contrib
-      uses: ./configure-and-build
-      with:
-        workdir: '${{ github.workspace }}'
-        builddir: 'build-contrib'
-        generator: '${{ matrix.vs }}'
-        options: '-A ${{ matrix.cmake_arch }} -DCMAKE_BUILD_TYPE=Release -DOPENCV_EXTRA_MODULES_PATH=opencv_contrib/modules ${{ env.CMAKE_OPT }}'
-
-    - name: Run OpenCV tests
-      uses: ./run-tests
-      env:
-        OPENCV_TEST_DATA_PATH: '${{ github.workspace }}/opencv_extra/testdata'
-        OPENCV_TEST_REQUIRE_DATA: 1
-        OPENCV_TEST_CHECK_OPTIONAL_DATA: 1
-        PYTHONPATH: '${{ github.workspace }}/${{ env.MAIN_BUILD_DIR }}/python_loader:$PYTHONPATH'
-      with:
-        workdir: '${{ github.workspace }}'
-        builddir: '${{ env.MAIN_BUILD_DIR }}'
-        logdir: '${{ github.workspace }}'
-        plan: "test-plan-win-4.x.json"
-        suite: "[ ${{ (github.event.repository.name == 'opencv_contrib') && '''contrib''' || '''main''' }} ]"
-        enable_python: "false"
-        enable_java: "false"
-        filter: "[ 'windows-common' ]"
-        suffix: "${{ matrix.arch }}_4.x"
-        timeout: 15
-
-    - if: ${{ always() && env.WARNINGS == '1' }}
-      name: Warnings check
-      run: |
-        echo "::error Warnings have been found!"
-        exit 1
